# Generated by Django 5.1.3 on 2024-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="fb_link",
            field=models.URLField(default="text"),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="ig_link",
            field=models.URLField(default="text"),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="occupation",
            field=models.CharField(default="text", max_length=250),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="bio",
            field=models.TextField(default="text"),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="gender",
            field=models.CharField(default="text", max_length=6),
        ),
    ]
