# Generated by Django 5.1.3 on 2024-11-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_generalinfo_fb_link_generalinfo_ig_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=7
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=400, null=True)),
                ("occupation", models.CharField(max_length=250)),
                ("fb_link", models.URLField()),
                ("ig_link", models.URLField()),
                ("linkedIn_link", models.URLField()),
                ("x_link", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="linkedIn_link",
            field=models.URLField(default="text"),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="x_link",
            field=models.URLField(default="text"),
        ),
    ]
